[colors.bright]
black = "0x72696a"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.dim]
black = "0x72696a"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.normal]
black = "0x72696a"
blue = "0xf38d70"
cyan = "0x85dacc"
green = "0xadda78"
magenta = "0xa8a9eb"
red = "0xfd6883"
white = "0xfff1f3"
yellow = "0xf9cc6c"

[colors.primary]
background = "0x2D2A2E"
foreground = "0xfff1f3"

[font]
size = 8.0

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[font.normal]
family = "JetBrainsMono"
style = "Regular"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
