theme = "gruvbox_dark_hard"

[editor]
idle-timeout = 0
completion-trigger-len = 10
auto-info = true
true-color = true
line-number = "relative"
auto-completion = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false
ignore = false
git-ignore = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
